version: '3.8'

networks:
  sakana-san-network:
    driver: bridge

services:
  sakana-san-api:
    image: 'noephilippe/sakana-san-api:latest'
    container_name: sakana-san-api
    restart: always
    env_file: .env
    volumes:
      - upload:/app/public/files
    ports:
      - '8001:8000'
    depends_on:
      - sakana-san-db
    networks:
      - sakana-san-network

  sakana-san-db:
    image: 'postgres:14.5-alpine'
    command: postgres -c 'max_connections=1000'
    restart: always
    container_name: sakana-san-db
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - sakana-san-network

volumes:
  upload:
  db:
